baseurl = "https://heuristic-mcnulty-f865bf.netlify.com/"
languageCode = "en-us"
paginate = 5
theme = "hello-friend"
[languages.en]
copyright = ""
keywords = ""
menuMore = "Show more"
newerPosts = "Newer posts"
olderPosts = "Older posts"
readMore = "Read more"
readOtherPosts = "Read other posts"
subtitle = "Subtitle"
title = "WhoisHou"
writtenBy = "Written by"
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
[[languages.en.menu.main]]
identifier = "showcase"
name = "Showcase"
url = "/showcase"
[languages.en.params.logo]
logoHomeLink = "/"
logoText = "WhoisHou"
[params]
contentTypeName = "posts"
defaultTheme = "dark"
showMenuItems = 2
